import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Bot, CalendarCheck2, CircleAlert, Sparkles, Users, Zap } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import PerformanceLayout from "../../components/layout/PerformanceLayout";
import { performanceRequest, scoreLabel } from "../../lib/performanceApi";
import type { AnalyticsOverview } from "../../lib/performanceApi";
import "../Employees/performance.css";

const COLORS = ["#2563eb", "#14b8a6", "#8b5cf6", "#f59e0b", "#ec4899", "#06b6d4"];
export default function Dashboard() {
  const [data, setData] = useState<AnalyticsOverview | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    performanceRequest<AnalyticsOverview>("/analytics/overview")
      .then(setData).catch((err: Error) => setError(err.message)).finally(() => setLoading(false));
  }, []);
  const summary = data?.summary;
  return <PerformanceLayout>
    <div className="performance-page-header dashboard-performance-header"><div><span className="performance-eyebrow">WORKSPHERE · PEOPLE INTELLIGENCE</span><h1>Performance dashboard</h1><p>Clear, data-backed insight into employee performance and team health.</p></div><Link to="/ai" className="performance-primary-button"><Sparkles size={16} /> Ask WorkSphere AI</Link></div>
    {error && <div className="performance-alert error">{error}</div>}
    {loading ? <div className="performance-panel performance-loading">Loading workspace performance…</div> : data && <>
      <section className="analytics-summary-row dashboard-kpis dashboard-kpis-six">
        <div className="performance-metric-card"><span><Users size={16} /> Total employees</span><strong>{summary?.totalEmployees ?? 0}</strong><p>{summary?.activeEmployees ?? 0} currently active</p></div>
        <div className="performance-metric-card"><span><Zap size={16} /> Average performance</span><strong>{summary?.averagePerformance.toFixed(1)}<small>/100</small></strong><p>Equal average of five metrics</p></div>
        <div className="performance-metric-card"><span><Sparkles size={16} /> Top performer</span><strong className="dashboard-top-score">{summary?.topPerformer?.name ?? "—"}</strong><p>{summary?.topPerformer ? `${Number(summary.topPerformer.performanceScore).toFixed(1)} / 100 · ${summary.topPerformer.department}` : "No employee records"}</p></div>
        <div className="performance-metric-card"><span><CircleAlert size={16} /> Needs attention</span><strong>{summary?.needingAttention ?? 0}</strong><p>Score below 75; review context</p></div>
        <div className="performance-metric-card"><span><Zap size={16} /> Average productivity</span><strong>{summary?.averageProductivity.toFixed(1)}<small>/100</small></strong><p>Across employee records</p></div>
        <div className="performance-metric-card"><span><CalendarCheck2 size={16} /> Average attendance</span><strong>{summary?.averageAttendance.toFixed(1)}<small>/100</small></strong><p>Across active and inactive staff</p></div>
      </section>
      {summary?.totalEmployees === 0 && <section className="performance-panel dashboard-first-employee"><span className="ai-icon"><Users size={20}/></span><div><h2>Your employee workspace is ready</h2><p>This account has no employee profiles yet. Add your first profile to start seeing private performance metrics, analytics, and AI insights.</p></div><Link to="/employees" className="performance-primary-button">Add employees <ArrowRight size={15}/></Link></section>}
      <div className="dashboard-performance-grid">
        <section className="performance-panel dashboard-chart-panel dashboard-chart-wide"><div className="performance-panel-heading"><div><h2>Employee performance comparison</h2><p>Top employees ranked by the calculated five-metric score.</p></div></div><div className="performance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.performanceByEmployee.slice(0,10)} layout="vertical" margin={{left:24,right:18}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" domain={[0,100]}/><YAxis type="category" dataKey="name" width={115} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="performanceScore" name="Performance" fill="#2563eb" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></section>
        <section className="performance-panel dashboard-chart-panel dashboard-chart-wide"><div className="performance-panel-heading"><div><h2>Performance over time</h2><p>Organization monthly average across recorded metrics.</p></div></div><div className="performance-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.monthlyPerformance}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis domain={[0,100]}/><Tooltip/><Line type="monotone" dataKey="performance" name="Performance" stroke="#2563eb" strokeWidth={3}/><Line type="monotone" dataKey="productivity" name="Productivity" stroke="#14b8a6" strokeWidth={2}/><Line type="monotone" dataKey="attendance" name="Attendance" stroke="#f59e0b" strokeWidth={2}/></LineChart></ResponsiveContainer></div></section>
        <section className="performance-panel dashboard-chart-panel"><div className="performance-panel-heading"><div><h2>Department comparison</h2><p>Average performance score.</p></div></div><div className="performance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.departmentPerformance}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="department"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="performance" name="Score" fill="#2563eb" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section>
        <section className="performance-panel dashboard-chart-panel"><div className="performance-panel-heading"><div><h2>People by department</h2><p>Current employee distribution.</p></div></div><div className="performance-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.departmentDistribution} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={52} outerRadius={82} paddingAngle={3}>{data.departmentDistribution.map((entry,index)=><Cell key={entry.name} fill={COLORS[index%COLORS.length]}/>)}</Pie><Tooltip/><text x="50%" y="49%" textAnchor="middle" dominantBaseline="middle" className="donut-total">{summary?.totalEmployees}</text><text x="50%" y="59%" textAnchor="middle" className="donut-caption">employees</text></PieChart></ResponsiveContainer></div></section>
        <section className="performance-panel dashboard-chart-panel dashboard-chart-wide"><div className="performance-panel-heading"><div><h2>Attendance vs productivity</h2><p>Each point represents one employee; hover to compare scores.</p></div></div><div className="performance-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:12,right:22,bottom:12,left:4}}><CartesianGrid/><XAxis type="number" dataKey="attendance" name="Attendance" domain={[0,100]}/><YAxis type="number" dataKey="productivity" name="Productivity" domain={[0,100]}/><ZAxis type="number" dataKey="performanceScore" name="Performance" range={[60,180]}/><Tooltip cursor={{strokeDasharray:"3 3"}}/><Scatter data={data.attendanceProductivity} fill="#2563eb"/></ScatterChart></ResponsiveContainer></div></section>
      </div>
      <section className="performance-panel dashboard-performer-panel"><div className="performance-panel-heading"><div><h2>Performance snapshot</h2><p>Highest score and team members whose latest score is trending down.</p></div><Link to="/analytics" className="performance-secondary-button">Open analytics <ArrowRight size={15}/></Link></div><div className="dashboard-snapshot-grid"><div className="dashboard-top-performer"><span className="ai-icon"><Sparkles size={18}/></span><div><small>Top performer</small><strong>{summary?.topPerformer?.name || "Not available"}</strong><span>{summary?.topPerformer ? `${summary.topPerformer.department} · ${Number(summary.topPerformer.performanceScore).toFixed(1)} · ${scoreLabel(Number(summary.topPerformer.performanceScore))}` : "Add employees to see a comparison"}</span></div><Link to={summary?.topPerformer ? `/employees/${summary.topPerformer.id}` : "/employees"}>View profile</Link></div><div className="dashboard-declines"><strong>Recent declines</strong>{summary?.decliningEmployees.length ? summary.decliningEmployees.slice(0,4).map((person)=><div key={person.name}><span>{person.name}<small>{person.department}</small></span><b>{person.trendDelta.toFixed(1)} pts</b></div>) : <p>No large month-over-month declines in the current data.</p>}</div></div><div className="dashboard-quick-links"><Link to="/employees"><Users size={17}/> Manage employees</Link><Link to="/analytics"><Zap size={17}/> Explore analytics</Link><Link to="/ai"><Bot size={17}/> Ask the AI assistant</Link></div></section>
    </>}
  </PerformanceLayout>;
}
